### PR TITLE
Django 1.8 full compability

### LINKED ISSUE #299: Error in Django 1.8b2
Exception Value: 'guardian_tags' is not a valid tag library: ImportError raised loading guardian.templatetags.guardian_tags: cannot import name get_library

### PR DESCRIPTION
**Pull request by bsvetchine**
Fixes all Django 1.8 compatibilities problems without breaking backward compatibilities.

Fixes #299,  #303

### CODE REVIEW

**Comment by AGASS007** [comment]
:+1:

**Comment by lukaszb** [comment]
**Thank you!**

Going to update tox/travis, run it there and merge if green.

**Comment by bsvetchine** [comment]
Hello Lukasz,

I updated tox and travis files to test guardian under Django 1.8. All tests run sucessfully.

Please note that I had to update the 0001 migration in the testapp due to a behaviour change with the User last_login field in Django 1.8.
https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#fields

**Comment by lukaszb** [comment]
@bsvetchine looks awesome. Will review it more closely in the evening but it seems to be good. One quick thing - does `tox` actually work? I mean, it seems `py27-django18` and `py34-django18` are missing entries in the config. And there is no Python 3.3 entry at all.

**Comment by bsvetchine** [comment]
@lukaszb you were right, the tox.ini django18 config were not registered. I added py33-django18 config and registered all django18 config.

**Comment by lukaszb** [comment]
@bsvetchine perfect, thanks!

**Comment by wldcordeiro** [comment]
@lukaszb with this merged in can we get a 1.2.6 tag made and pushed to PyPI?

**Comment by frwickst** [comment]
I don't think that we are ready for a release yet saying that there is full 1.8 support as pull requests such as #311 are still active.

**Comment by troygrosfield** [comment]
+1 to getting #311 merged and getting this bad boy released so I can stop deploying from the master branch.  Let me know if there's anything I can do to push this along.

**Pull request merged**
