### PR TITLE
implemented global permission check in shortcuts for get_objects_for_use...

### PR DESCRIPTION
**Pull request by v-erena**
...r and get_objects_for_group

I implemented the checks directly within the functions. But: shouldn't this be inherently implemented in ObjectPermissionChecker.has_perm function? I am not sure, what side effects this would have, and if this is desired at all..

### CODE REVIEW

**Comment by aidanlister** [comment]
PR looks well thought out and well tested

**Comment by lukaszb** [comment]
@aidanlister thank you! I honestly don't have much time to go through those changes so am merging based on your opinion.

**Comment by aidanlister** [comment]
Alright that scares me a little bit but I'll pull this into production and feed back with any issues.

**Comment by lukaszb** [comment]
@aidanlister haha, wondered if you feel it ;-) Good to hear I'm not the only one that worried. But seriously, before I put release comment I'm going to go through it more closely anyway ;-)

**Comment by v-erena** [comment]
happy to have any feedback on that, and of course, eager to contribute further ;-)

**Pull request merged**
